### ISSUE TITLE
Can Z2pack calculate the Berry phase along a cirlce?

### ISSUE THREAD

**Issue by sliutheory** [Z2PackDev/Z2Pack#101]
I would like to calculate the berry phase along a circle using Quantum Espresso.

Can Z2pack do that?

I guess I need to modify shape.py?

Thank you!

**Comment by greschd** [comment]
Yes, with newer Wannier90 and `pw2wannier90` versions that is possible. Two things are needed:

- The k-points need to be passed to QE in "explicit" mode, and to Wannier90 in "full" mode. To do so, use the `kpt_fct` as in this example when constructing the system:

https://github.com/Z2PackDev/Z2Pack/blob/b5c42630db04568eb84210abecd50946370d1c3b/examples/fp/espresso/6/MoP2_weyl/run.py#L63

- There's no need to modify `shape.py`: The `line.run` and `surface.run` functions can take any function that parametrizes the shape on which the WCC should be calculated. The `shape.py` module simply provides some useful ones for common uses. So, for a circle, you could do e.g.

```python
import numpy as np

system = ...
x0, y0, z0 = ... # center of the circle
r = ... # radius

z2pack.line.run(
    system=system,
    line=lambda t: [x0 + r * np.cos(2 * np.pi * t), y0 + r * np.sin(2 * np.pi * t), z0]
)
```

Of course you can also modify this to e.g. be oriented in a different way. The only important point is that the line is closed, i.e. t=0 and t=1 describe the same point (up to lattice translations).

**Comment by sliutheory** [comment]
Thank you. Yes, indeed it works. 
A minor question. The values of  res.wcc (say res=z2pack.line.run) are in the unit of 2pi or pi?

**Comment by greschd** [comment]
The values are normalized to the interval [0, 1).

**Comment by greschd** [comment]
I'm closing this since it seems the original question is answered - feel free to open another issue if needed.
