### ISSUE TITLE
Computing Z2 number from a completed vasp-wannier90 run

### ISSUE THREAD

**Issue by shahid-sattar** [Z2PackDev/Z2Pack#211]
Dear Developers, 
New user to Z2pack and using VASP+wannier90,  Can I compute Z2 number from a completed vasp-wannier90 run (meaning having .mmn, .amn, .eig and .chk files)? 
For example, I calculated wannier projections of Bi2Se3 bulk. Can the output be used directly to compute Z2 number?
Thanks in advance,

**Comment by greschd** [comment]
Hi @shahid-sattar 👋

No, this is not possible: Z2Pack needs to run the NSCF+Wannier90 step multiple times, dynamically changing which k-points are considered.

In principle a Z2 invariant (without any convergence criteria applied) could be computed from the ``.mmn`` files of a static VASP + Wannier90 run, but this is not implemented in Z2Pack.

**Comment by shahid-sattar** [comment]
thanks for the response. I understand.
