### ISSUE TITLE
questions about the surface definition

### ISSUE THREAD

**Issue by tron1989** [Z2PackDev/Z2Pack#48]
First, I think there is an mistake in the website (http://z2pack.ethz.ch/doc/2.0/tutorial_surface.html#basic-syntax) about the equation

f(t1,0)=f(t2,1) +G , here, I think t2 should be t1.

Second,  when I want to calculate Z2 with vasp, I define the surface with
 surface=lambda s, t: [s, t/2, 0]
There is an error

>  ValueError: The k-points must be aligned in (positive) kx-, ky- or kz-direction for VASP runs.

Otherwise, when I try **surface=lambda s, t: [t, s/2, 0]** there is no error

I was quite confusing about the surface definition, which is written
surface=lambda t1, t2: [t1, t2, 0]

As the tutorials says, t2 is the direction Wannier charge centers are calculated. So the order of t1, t2 is quite important . So how can I USE the surface definition properly?

**Comment by greschd** [comment]
First, that's indeed a typo (should be t1 on both sides), thanks for noticing.

The other behaviour is intended: The WCC must be calculated along a line which is periodic (that is, the final point is the same up to a lattice vector as the first one). A line is given for a fixed value of the first parameter (called ``s`` here, or ``t1`` in the tutorial), and varying the second parameter from 0 to 1.

So when you use ``lambda s, t: [s, t / 2, 0]``, this is not fulfilled: the last point on a given line is at y=0.5 instead of y=1. ``lambda s, t: [s / 2, t, 0]`` however works because the condition is fulfilled. Both define the same surface, but only the second version also fulfils the condition that each line must be periodic.

**Comment by tron1989** [comment]
I have some tests on one system now I am interested with Z2pack both version 1.1 and 2.0.2. The system is calculated **without SOC**. However, they give different results.

Here, I give the surface syntax below:
**Version 1.1**

`
surface = system.surface(lambda t: [0, t / 2, 0], [1, 0, 0],
                           pickle_file = './results/res_0.txt')
`
 **Version 2.0.2**


```
result_0 = z2pack.surface.run(
    system=system,
    surface=lambda s, t: [s/2., t, 0],
    save_file = './results/res_1.p',
    load=True,
    num_lines=51,
    min_neighbour_dist=0.02
)

```
I think the surface should be the same surface by definition.  My system has a direct gap with 650 meV.

Also, I have tested with the **wannier90_hr.dat**, it give the same results with version 1.1 which indicated the system is trival.

Is the problem lied in the Convergence options?

**Comment by greschd** [comment]
No, it's because the two surfaces are different. If you want the same surface, it should be 

    surface = system.surface(lambda t: [t / 2, 0, 0], [0, 1, 0], pickle_file = './results/res_0.txt')

in version 1.1. This is because the second parameter corresponds to the direction along which the WCC are calculated, which is the ``string_vec`` argument in 1.1.

**Comment by tron1989** [comment]
OKay, I think I have to read the tutorials more carefully and strength my knowledge of Python. 

But questions again, as the system is 2D with time reversal symmetry, the results with two surfaces should be the same in my opinion.

**Comment by greschd** [comment]
The Z2 invariant should be the same, yes. The Wannier charge centers themselves and the plots could be different.

**Comment by tron1989** [comment]
Thanks. When will your paper "Universal framework for identifying topological materials and its numerical implementation" come out ? I just cannot wait to read it!

**Comment by greschd** [comment]
Very soon I hope... it is in review with our collaborators.

**Comment by tron1989** [comment]
Good luck!

I have so many navie questions to ask about the calculations of topological invariants. But, I think I have to stop to think it over by myself to get a better understanding.

**Comment by greschd** [comment]
Thanks! 

Feel free to check back to ask questions when you're stuck with something.
