### ISSUE TITLE
Z2pack for 2D systems using VASP

### ISSUE THREAD

**Issue by fmatusalem** [Z2PackDev/Z2Pack#50]
Hello, 

I trying to use Z2pack to get WCC evolution curves for a 2D graphene-like system, calculated with VASP. 
To understand how Z2pack work I tried to compute the example Bi_vasp but got some errors with the module  z2pack.surface.plot.wcc : 

Traceback (most recent call last):
  File "run.py", line 50, in <module>
    z2pack.surface.plot.wcc(result_0, axis=ax[0])
AttributeError: module 'z2pack.surface' has no attribute 'plot'

Removing the word surface  (z2pack.plot.wcc ) the module works but the figure does not look like the one in the folder plot, the open circles do not appear, only the blue diamonds show up.

The same error holds for z2pack.surface.invariant.z2 module. 

Some idea why this is happening? 

Also, if possible, could you give an example of a run.py file to plot the WCC curves for a 2D systems?

Thank you

Filipe Matusalem

**Comment by tron1989** [comment]
I think I can answer your question.

The example is out of date. The new plotting module is z2pack.plot.wcc. Checking the source codes, the default parameters could be found as below:
`def wcc(
        surface_result,
        *,
        axis=None,
        wcc_settings={'s': 50., 'lw': 1., 'facecolor': 'none'},
        gaps=True,
        gap_settings={'marker': 'D', 'color': 'b', 'linestyle': 'none'}
)
`

If you want to get the shapes of wcc, you should set ` wcc_settings` with` 'maker': 'o'`, the you should get open circles.

For 2D systems with time reversal symmetry, you should set kz=0, and choose one direction as the wcc evaluates.

**Comment by greschd** [comment]
Indeed, the example was out of date -- I fixed it now.

As for the missing circles, I'm not sure why this happens. The keywords given in ``wcc_settings`` are passed to [matplotlib scatter](http://matplotlib.org/api/axes_api.html?highlight=scatter#matplotlib.axes.Axes.scatter) which produces the WCC part of the plot. You can try just passing an empty dict (``wcc_settings={}``), and see what this produces.

Which matplotlib version are you using? Maybe the default values changed such that the markers are invisible when the the values ``{'s': 50., 'lw': 1., 'facecolor': 'none'}`` are passed.

**Comment by greschd** [comment]
The problem  appears when using matplotlib 2.x, because the edge color is by default the same as the fill color (instead of just black). You can fix it by using
 ``wcc_settings={'lw': 1.0, 'facecolor': 'none', 's': 50.0, 'edgecolors': 'k'}``

I will also update the default values accordingly, to work with the new matplotlib release.

**Comment by fmatusalem** [comment]
Thank you for the answer. The matplotlib version is 2.0. With the change in wcc_settings the open circles appeared correctly.

**Comment by ahzeeshan** [comment]
@tron1989 I have a question about defining the surface.
> For 2D systems with time reversal symmetry, you should set kz=0, and choose one direction as the wcc evaluates.

So, will the surface defined this way be enough to compute the Z2 invariant for a 2D system? Thanks.
`result_0 = z2pack.surface.run(
    system=system,
    surface=lambda s, t: [s / 2, t, 0],
    save_file='./results/res_0.json',
    load=True
)`

**Comment by greschd** [comment]
If the 2D system is defined such that it's extended in x and y directions (in reciprocal coordinates), then yes, that's the correct way to do it.
