### ISSUE TITLE
How to print the WCC evolution in a text format file

### ISSUE THREAD

**Issue by fmatusalem** [Z2PackDev/Z2Pack#51]
I would like to known how to generate a file in a text format in such a way one could plot the WCC evolution using a different graphic program then matplotlib. 

Thanks.

**Comment by greschd** [comment]
You can get the WCC via the ``.wcc`` attribute of your result. This gives you a nested list of WCC for each line, which you can print in any way you like.
If you need the positions of the lines to which these correspond, you can use the ``.t`` attribute of the result.

    result = z2pack.surface.run(...)
    print(result.wcc)
    print(result.t)

**Comment by fmatusalem** [comment]
Ok, thanks.
