### ISSUE TITLE
Problem with kpoints function interfacing with VASP

### ISSUE THREAD

**Issue by anhph** [Z2PackDev/Z2Pack#55]
Hi,

I'm currently testing the Z2pack interfacing with VASP to calculate the Z2invariant of a simple cubic structure. It seems like the kpoints function for vasp doesn't work well with the simple cubic system. The shifting of the kpoints origin creates error like "internal error in subroutine SGRCON", and this terminates the calculation  when the KPOINTS is shifted from 0,0,0. Any help would be greatly appreciated.

Thanks,
Anh

**Comment by greschd** [comment]
Hi Anh,

My best guess is that you need to set ``ISYM = -1``. If this doesn't work I'd have to see the input files to figure out what is going on.

Best regards,
Dominik

**Comment by anhph** [comment]
Hi Dominik,

Thanks, it works. Previously i used ISYM=0, and i think vasp still preserves certain symmetry which creates this error.

Anh

**Comment by greschd** [comment]
Ok, glad I could help.
Dominik
