### ISSUE TITLE
MAGMOM tag in example Bi_vasp

### ISSUE THREAD

**Issue by Djordje117** [Z2PackDev/Z2Pack#71]
Why was MAGMOM tag set to 36 * 0.0? When I read VASP documentation, it states that 

MAGMOM =  3*NIONS*1.0 for non-collinear magnetic systems. Since there are 2 ions in that system, shouldn't MAGMOM be 6*0.0?

Kind regards,

Dorde

**Comment by greschd** [comment]
As far as I am aware, setting the `MAGMOM` array to have _more_ entries than there are ions will mean VASP just ignores the superfluous ones. That means the results should be the same for 6 * 0.0 or 36 * 0.0.

We might as well change it to 6 * 0.0 however, to avoid any confusion.
