### ISSUE TITLE
The KPOINT file problem

### ISSUE THREAD

**Issue by abduljalils** [Z2PackDev/Z2Pack#72]
Dear Developers:
I am new user of Z2PACK ,I am using vasp in previous calculations I have linked wannier to vasp and tested example Bi_VASP. The jobs start and generate files in build folder, but after few electronic steps stopped,the error is given below,
```
 VERY BAD NEWS! internal error in subroutine IBZKPT:
 Reciprocal lattice and k-lattice belong to different class of lattices. Often results are still useful...      48
VERY BAD NEWS! internal error in subroutine IBZKPT:
 Reciprocal lattice and k-lattice belong to different class of lattices. Often results are still useful...      4
 WARNING: stress and forces are not correct
 POSCAR, INCAR and KPOINTS ok, starting setup
 FFT: planning ...
 WAVECAR not read
 reading imaginary part of occupancies ...
 charge-density read from file: Bi
 reading imaginary part of occupancies ...
 magnetization density read from file 1
 reading imaginary part of occupancies ...
 magnetization density read from file 2
 reading imaginary part of occupancies ...
 magnetization density read from file 3
 entering main loop
       N       E                     dE             d eps       ncg     rms          rms(c)
DAV:   1     0.271658275518E+02    0.27166E+02   -0.26447E+03   336   0.361E+02
DAV:   2    -0.185943397622E+01   -0.29025E+02   -0.28660E+02   480   0.611E+01
DAV:   3    -0.254807417070E+01   -0.68864E+00   -0.68864E+00   336   0.144E+01
DAV:   4    -0.255688183451E+01   -0.88077E-02   -0.88077E-02   648   0.165E+00
DAV:   5    -0.255688457330E+01   -0.27388E-05   -0.27390E-05   384   0.271E-02
DAV:   6    -0.255688460799E+01   -0.34691E-07   -0.34037E-07   648   0.219E-03
wannier90 error: examine the output/error file for details
forrtl: error (78): process killed (SIGTERM)
Image              PC                Routine            Line        Source
vasp-wannier.1.2_  0000000001143FCD  Unknown               Unknown  Unknown
vasp-wannier.1.2_  0000000001141E67  Unknown               Unknown  Unknown
vasp-wannier.1.2_  00000000010CE074  Unknown               Unknown  Unknown
```

> `1. run.py file is given below,

```
/usr/bin/env python
 coding: utf-8 -*-

import sys
sys.path.append('/public/home/abdul/Z2PACK/Z2Pack-master-2.1.x')

import os
          
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
        
import z2pack 
             
#vaspdir = '/public/home/wudx/app/vasp.5.4.1-with-wannier.1.2/bin/'
#wandir = '/public/home/wudx/app/wannier90-1.2'

 Creating the System. Note that the SCF charge file does not need to be
 copied, but instead can be referenced in the .files file.
The k-points input is appended to the .in file
The command (mpirun ...) will have to be replaced to match your system.
system = z2pack.fp.System(
    input_files=["input/CHGCAR", "input/INCAR", "input/POSCAR", "input/POTCAR", "input/wannier90.win" ],
    kpt_fct=z2pack.fp.kpoint.vasp,
    kpt_path="KPOINTS",
    command="mpirun -np 24 /public/home/wudx/app/vasp.5.4.1-with-wannier.1.2/bin/vasp-wannier.1.2_ncl >& log"
    #command="mpirun $VASP >& log"
)

if not os.path.exists('./results'):
    os.mkdir('./results')
if not os.path.exists('./plots'):
    os.mkdir('./plots')


 Running the WCC calculation - standard settings
result_0 = z2pack.surface.run(
    system=system,
    surface=lambda s, t: [0, s / 2, t],
    save_file = './results/res_0.p',
    load=True
)
result_1 = z2pack.surface.run(
    system=system,
    surface=lambda s, t: [0.5, s / 2, t],
    save_file = './results/res_1.p',
    load=True
)

Plotting WCC evolution
fig, ax = plt.subplots(1, 2, sharey=True, figsize = (9,5))

z2pack.plot.wcc(result_0, axis=ax[0])
z2pack.plot.wcc(result_1, axis=ax[1])
plt.savefig('plots/plot.pdf', bbox_inches = 'tight')

print('Z2 topological invariant at kx = 0: {0}'.format(z2pack.invariant.z2(result_0)))
print('Z2 topological invariant at kx = 0.5: {0}'.format(z2pack.invariant.z2(result_1)))
```

**Comment by greschd** [comment]
It seems the problem doesn't occur during the startup phase (where the k-point warning is shown), but after the NSCF steps have converged. This leads me to believe that it might be a problem with the VASP / Wannier interface.

Did you get any error files from either VASP or Wannier90? Also, make sure you follow the installation instructions from http://z2pack.ethz.ch/doc/2.1/tutorial/installation.html#setting-up-first-principles-codes

**Comment by abduljalils** [comment]
Actually, in previous calculations, I have tested  vasp interface wannier90 successfully on many systems.But after installation of Z2Pack this error occured.please have a look to 
**wannnier.wout**
            |         Localised Wannier Functions"              |
             |        A. A. Mostofi, J. R. Yates, Y.-S. Lee,     |
             |        I. Souza, D. Vanderbilt and N. Marzari     |
             |        Comput. Phys. Commun. 178, 685 (2008)      |
             |                                                   |
             |  in any publications arising from the use of      |
             |  this code. For the method please cite            |
             |                                                   |
             |  [ref] "Maximally Localized Generalised Wannier   |
             |         Functions for Composite Energy Bands"     |
             |         N. Marzari and D. Vanderbilt              |
             |         Phys. Rev. B 56 12847 (1997)              |
             |                                                   |
             |  [ref] "Maximally Localized Wannier Functions     |
             |         for Entangled Energy Bands"               |
             |         I. Souza, N. Marzari and D. Vanderbilt    |
             |         Phys. Rev. B 65 035109 (2001)             |
             |                                                   |
             |                                                   |
             | Copyright (c) 1996-2010                           |
             |        A. A. Mostofi, J. R. Yates, Y.-S. Lee,     |
             |        I. Souza, D. Vanderbilt and N. Marzari     |
             |                                                   |
             |        Release: 1.2        24th Jan 2010          |
             |                                                   |
             | This program is free software; you can            |
             | redistribute it and/or modify it under the terms  |
             | of the GNU General Public License as published by |
             | the Free Software Foundation; either version 2 of |
             | the License, or (at your option) any later version|
             |                                                   |
             | This program is distributed in the hope that it   |
             | will be useful, but WITHOUT ANY WARRANTY; without |
             | even the implied warranty of MERCHANTABILITY or   |
             | FITNESS FOR A PARTICULAR PURPOSE. See the GNU     |
             | General Public License for more details.          |
             |                                                   |
             | You should have received a copy of the GNU General|
             | Public License along with this program; if not,   |
             | write to the Free Software Foundation, Inc.,      |
             | 675 Mass Ave, Cambridge, MA 02139, USA.           |
             |                                                   |
             +---------------------------------------------------+
             |    Execution started on 18Apr2018 at 22:35:08     |
             +---------------------------------------------------+

 Wannier90 is running in LIBRARY MODE

 Setting up k-point neighbours...


 Ignoring <num_bands> in input file
 Ignoring <spinors> in input file

                                    ------
                                    SYSTEM
                                    ------

                              Lattice Vectors (Ang)
                    a_1     4.745800   0.000000   0.000000
                    a_2     2.568510   3.990660   0.000000
                    a_3     2.568510   1.401370   3.736510

                   Unit Cell Volume:      70.76529  (Ang^3)

                        Reciprocal-Space Vectors (Ang^-1)
                    b_1     1.323947  -0.852132  -0.590502
                    b_2     0.000000   1.574473  -0.590503
                    b_3     0.000000   0.000000   1.681565

 *----------------------------------------------------------------------------*
 |   Site       Fractional Coordinate          Cartesian Coordinate (Ang)     |
 +----------------------------------------------------------------------------+
 | Bi   1   0.23389   0.23389   0.23389   |    2.31149   1.26114   0.87393    |
 | Bi   2   0.76611   0.76611   0.76611   |    7.57133   4.13089   2.86258    |
 *----------------------------------------------------------------------------*

                                ------------
                                K-POINT GRID
                                ------------

             Grid size =  1 x  1 x  7      Total points =    7


 *---------------------------------- MAIN ------------------------------------*
 |  Number of Wannier Functions               :                10             |
 |  Number of input Bloch states              :                18             |
 |  Output verbosity (1=low, 5=high)          :                 1             |
 |  Timing Level (1=low, 5=high)              :                 1             |
 |  Optimisation (0=memory, 3=speed)          :                 3             |
 |  Length Unit                               :               Ang             |
 |  Post-processing setup (write *.nnkp)      :                 F             |
 |  Using Gamma-only branch of algorithms     :                 F             |
 *----------------------------------------------------------------------------*
 *------------------------------- WANNIERISE ---------------------------------*
 |  Total number of iterations                :                 0             |
 |  Number of CG steps before reset           :                 5             |
 |  Trial step length for line search         :             2.000             |
 |  Convergence tolerence                     :         0.100E-09             |
 |  Convergence window                        :                -1             |
 |  Iterations between writing output         :                 1             |
 |  Iterations between backing up to disk     :               100             |
 |  Write r^2_nm to file                      :                 F             |
 |  Write xyz WF centres to file              :                 F             |
 |  Use guiding centre to control phases      :                 F             |
 *----------------------------------------------------------------------------*
 Time to read parameters        0.002 (sec)

 *---------------------------------- K-MESH ----------------------------------*
 +----------------------------------------------------------------------------+
 |                    Distance to Nearest-Neighbour Shells                    |
 |                    ------------------------------------                    |
 |          Shell             Distance (Ang^-1)          Multiplicity         |
 |          -----             -----------------          ------------         |
 |             1                   0.240224                      2            |
 |             2                   0.480447                      2            |
 |             3                   0.720671                      2            |
 |             4                   0.960894                      2            |
 |             5                   1.201118                      2            |
 |             6                   1.441342                      2            |
 |             7                   1.508315                      2            |
 |             8                   1.524158                      2            |
 |             9                   1.530485                      2            |
 |            10                   1.576870                      2            |
 |            11                   1.578314                      4            |
 |            12                   1.579844                      4            |
 +----------------------------------------------------------------------------+
 | The b-vectors are set in the win file                                      |
 Exiting.......
 kmesh_shell_fixed: B1 condition not satisfied.

**run.py**
[abdul@dawn4 Bi_vasp]$ python3 run.py 

+----------------------------------------------------------------------+
|===================                                                   |
|SURFACE CALCULATION                                                   |
|===================                                                   |
|starting at 2018-04-19 19:26:16,511                                   |
|running Z2Pack version 2.1.1a0                                        |
|                                                                      |
|gap_tol:            0.3                                               |
|init_result:        None                                              |
|iterator:           range(8, 27, 2)                                   |
|load:               True                                              |
|load_quiet:         True                                              |
|min_neighbour_dist: 0.01                                              |
|move_tol:           0.3                                               |
|num_lines:          11                                                |
|pos_tol:            0.01                                              |
|save_file:          ./results/res_0.p                                 |
|serializer:         auto                                              |
|surface:            <function <lambda> at 0x7f125c779bf8>             |
|system:             <z2pack.fp._first_prin<...>ject at 0x7f12844cd978>|
+----------------------------------------------------------------------+

INFO: Adding lines required by 'num_lines'.
INFO: Adding line at t = 0.0
INFO:       Calculating line for N = 8
Traceback (most recent call last):
  File "/public/home/abdul/.local/lib/python3.6/site-packages/z2pack/fp/_read_mmn.py", line 16, in get_m
    with open(mmn_file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/public/home/abdul/Z2PACK/Z2Pack-master-2.1.x/examples/fp/Bi_vasp/build/wannier90.mmn'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run.py", line 41, in <module>
    load=True
  File "/public/home/abdul/.local/lib/python3.6/site-packages/z2pack/surface/_run.py", line 149, in run_surface
    serializer=serializer
  File "/public/home/wanyang/software/python-3.6.1/lib/python3.6/contextlib.py", line 53, in inner
    return func(*args, **kwds)
  File "/public/home/abdul/.local/lib/python3.6/site-packages/z2pack/surface/_run.py", line 277, in _run_surface_impl
    result = add_line(t)
  File "/public/home/abdul/.local/lib/python3.6/site-packages/z2pack/surface/_run.py", line 221, in add_line
    data.add_line(t, get_line(t))
  File "/public/home/abdul/.local/lib/python3.6/site-packages/z2pack/surface/_run.py", line 194, in get_line
    init_result=init_line_result
  File "/public/home/abdul/.local/lib/python3.6/site-packages/z2pack/line/_run.py", line 202, in _run_line_impl
    list(np.array(line(k)) for k in np.linspace(0., 1., run_options['num_steps']))
  File "/public/home/abdul/.local/lib/python3.6/site-packages/z2pack/fp/_first_principles.py", line 138, in get_mmn
    M = mmn.get_m(self._mmn_path)
  File "/public/home/abdul/.local/lib/python3.6/site-packages/z2pack/fp/_read_mmn.py", line 56, in get_m
    raise type(err)((msg)) from err
FileNotFoundError: [Errno 2] No such file or directory: '/public/home/abdul/Z2PACK/Z2Pack-master-2.1.x/examples/fp/Bi_vasp/build/wannier90.mmn'. Check that the path of the .mmn file is correct (mmn_path input variable). If that is the case, an error occured during the call to the first-principles code and Wannier90. Check the corresponding log/error files.

**Comment by greschd** [comment]
This error happens because you're not using the modified Wannier90 version that works with Z2Pack. Wannier90 2.1+ works out of the box, but since VASP only supports Wannier90 1.x the modified version needs to be installed. Please follow the installation instructions linked above.

**Comment by abduljalils** [comment]
Right thank you.

**Comment by abduljalils** [comment]
Dear Prof:
Now I have installed modified version of wannier1.2 mentioned on z2pack
website,but unfortunately I got same error,
log:

 VERY BAD NEWS! internal error in subroutine IBZKPT:
 Reciprocal lattice and k-lattice belong to different class of lattices.
Often results are still useful...      48


 VERY BAD NEWS! internal error in subroutine IBZKPT:
 Reciprocal lattice and k-lattice belong to different class of lattices.
Often results are still useful...      48
 WARNING: stress and forces are not correct
 POSCAR, INCAR and KPOINTS ok, starting setup
 FFT: planning ...
 WAVECAR not read
 reading imaginary part of occupancies ...
 charge-density read from file: Bi
 reading imaginary part of occupancies ...
 magnetization density read from file 1
 reading imaginary part of occupancies ...
 magnetization density read from file 2
 reading imaginary part of occupancies ...
 magnetization density read from file 3
 entering main loop
       N       E                     dE             d eps       ncg
 rms          rms(c)
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
vasp_ncl           000000000180EA41  Unknown               Unknown  Unknown
vasp_ncl           000000000180D197  Unknown               Unknown



run.py

INFO: Adding lines required by 'num_lines'.
INFO: Adding line at t = 0.0
INFO:       Calculating line for N = 8
Traceback (most recent call last):
  File
"/opt/python-3.6.1/lib/python3.6/site-packages/z2pack/fp/_read_mmn.py",
line 16, in get_m
    with open(mmn_file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory:
'/home/cmss/abdul/Bi_vasp/build/wannier90.mmn'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cmss/abdul/.lsbatch/1524223485.58340.shell", line 45, in
<module>
    load=True
  File
"/opt/python-3.6.1/lib/python3.6/site-packages/z2pack/surface/_run.py",
line 149, in run_surface
    serializer=serializer
  File "/opt/python-3.6.1/lib/python3.6/contextlib.py", line 53, in inner
    return func(*args, **kwds)
  File
"/opt/python-3.6.1/lib/python3.6/site-packages/z2pack/surface/_run.py",
line 277, in _run_surface_impl
    result = add_line(t)
  File
"/opt/python-3.6.1/lib/python3.6/site-packages/z2pack/surface/_run.py",
line 221, in add_line
    data.add_line(t, get_line(t))
  File
"/opt/python-3.6.1/lib/python3.6/site-packages/z2pack/surface/_run.py",
line 194, in get_line
    init_result=init_line_result
  File "/opt/python-3.6.1/lib/python3.6/site-packages/z2pack/line/_run.py",
line 202, in _run_line_impl
    list(np.array(line(k)) for k in np.linspace(0., 1.,
run_options['num_steps']))
  File
"/opt/python-3.6.1/lib/python3.6/site-packages/z2pack/fp/_first_principles.py",
line 138, in get_mmn
    M = mmn.get_m(self._mmn_path)
  File
"/opt/python-3.6.1/lib/python3.6/site-packages/z2pack/fp/_read_mmn.py",
line 56, in get_m
    raise type(err)((msg)) from err
FileNotFoundError: [Errno 2] No such file or directory:
'/home/cmss/abdul/Bi_vasp/build/wannier90.mmn'. Check that the path of the
.mmn file is correct (mmn_path input variable). If that is the case, an
error occured during the call to the first-principles code and Wannier90.
Check the corresponding log/error files.





*ABDUL JALILLecturerDepartment of Physics00923315192550,0519057214*
*Allama Iqbal Open university,** Islamabad Pakistan.*
*http://www.aiou.edu.pk/ <http://www.aiou.edu.pk/>*

**Comment by greschd** [comment]
Since that's a segmentation fault in VASP (that didn't occur before), I'd guess there was an issue with the compilation of VASP. Maybe some library was not correctly linked or something similar. However, since I'm not an expert on compiling VASP I don't know what exactly might be the cause for that.

**Comment by greschd** [comment]
No, VASP does not support Wannier90 2.x as far as I'm aware.

**Comment by yargk** [comment]
I have the same error when running the Bi example for VASP with VASP 5.4.4 compiled with wannier90 3.1. According to this link (https://ntq1982.github.io/files/20200624.html), VASP 5.4.4 should work with wannier90 2.x and by extension wannier90 3 because the variable list is the same. However, since I'm getting the error this seems not to be the case. I'll compile VASP 5.4.4 with the modified wannier90 1.2 as well as 2.1 to see if those combinations work for me.

**Comment by greschd** [comment]
@yargk since there were some different errors discussed above, could you post the exact exception you are getting?

**Comment by yargk** [comment]
Thanks for the quick reply!
 WARNING: stress and forces are not correct
 POSCAR, INCAR and KPOINTS ok, starting setup
 FFT: planning ...
 WAVECAR not read
 reading imaginary part of occupancies ...
 charge-density read from file: Bi                                      
 reading imaginary part of occupancies ...
 magnetization density read from file 1
 reading imaginary part of occupancies ...
 magnetization density read from file 2
 reading imaginary part of occupancies ...
 magnetization density read from file 3
 entering main loop
       N       E                     dE             d eps       ncg     rms          rms(c)
DAV:   1     0.126615583382E+02    0.12662E+02   -0.27217E+03  1008   0.121E+02
DAV:   2    -0.239142146567E+01   -0.15053E+02   -0.15053E+02  1512   0.203E+01
DAV:   3    -0.247556715987E+01   -0.84146E-01   -0.84146E-01  1008   0.223E+00
DAV:   4    -0.247589432199E+01   -0.32716E-03   -0.32716E-03  2016   0.111E-01
DAV:   5    -0.247589432497E+01   -0.29726E-08   -0.32659E-08  1008   0.432E-04
DAV:   6    -0.247589432487E+01    0.97089E-10   -0.54094E-11  2016   0.152E-05
 kmesh_shell_fixed: B1 condition not satisfied
 Error on node 0: examine the output/error files for details
slurmstepd: error: *** STEP 8538499.0 ON quartz21 CANCELLED AT 2022-02-10T10:43:28 ***
srun: Job step aborted: Waiting up to 62 seconds for job step to finish.
srun: error: quartz21: task 0: Exited with exit code 1
srun: error: quartz21: tasks 1-35: Killed
srun: error: quartz22: tasks 36-71: Killed

**Comment by yargk** [comment]
By the way, I'm trying to compile the modified wannier90 1.2, however I don't see a readme that is specific to the modified version, yet the modified version doesn't have the same makefile as the unmodified version. Is there an installation readme for this special version of wannier90 1.2?

**Comment by greschd** [comment]
> Is that correct?

Yes, but since there are only 4 possible outputs it's obviously no guarantee that the calculation works correctly; you should probably check the plots (the hybrid Wannier charge center evolution should be continuous, without large jumps), and try some other materials (e.g. Bi2Se3, which has a non-trivial index).

> For the modified Wannier90 1.2 version, I think it's just missing Makefiles in the root directory and the src directory. I used the Makefiles from the normal 1.2 version and got it compiled, however I haven't tested it yet. (The result I got above was with VASP 5.4.4 and wannier90 3.1).

Ok, thanks for the info. Since VASP now supports the `skip_B1_tests` flag, there's not really a reason to use this modified version anymore.
